package hexlet.code.repository;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

import hexlet.code.TestcontainersConfig;
import hexlet.code.config.JpaConfig;
import hexlet.code.model.User;
import java.time.LocalDateTime;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.data.jpa.test.autoconfigure.DataJpaTest;
import org.springframework.boot.jdbc.test.autoconfigure.AutoConfigureTestDatabase;
import org.springframework.context.annotation.Import;
import org.springframework.dao.DataIntegrityViolationException;

@DataJpaTest
@AutoConfigureTestDatabase(replace = AutoConfigureTestDatabase.Replace.NONE)
@Import({TestcontainersConfig.class, JpaConfig.class})
class UserRepositoryTest {
    @Autowired private UserRepository repository;

    // --- helpers ---
    private User newUser(String email) {
        var user = new User();
        user.setFirstName("John");
        user.setLastName("Doe");
        user.setEmail(email);
        user.setPasswordDigest("$2a$10$abcdefghijklmnopqrstuv");
        return user;
    }

    // --- tests ---
    @Test
    void shouldPopulateIdAndAuditFieldsOnSave() {
        var saved = repository.saveAndFlush(newUser("audit@example.com"));

        assertThat(saved.getId()).as("id should be generated by identity").isNotNull().isPositive();

        assertThat(saved.getCreatedAt())
                .as("createdAt should be populated by @CreatedDate")
                .isNotNull()
                .isBeforeOrEqualTo(LocalDateTime.now());

        assertThat(saved.getUpdatedAt())
                .as("updatedAt should be populated by @LastModifiedDate")
                .isNotNull()
                .isBeforeOrEqualTo(LocalDateTime.now());
    }

    @Test
    void shouldRejectDuplicateEmail() {
        var email = "dup@example.com";
        repository.saveAndFlush(newUser(email));

        var duplicate = newUser(email);

        assertThatThrownBy(() -> repository.saveAndFlush(duplicate))
                .as("unique constraint uk_users_email should reject duplicate")
                .isInstanceOf(DataIntegrityViolationException.class);
    }

    @Test
    void shouldFindByEmail() {
        var email = "find@example.com";
        var saved = repository.saveAndFlush(newUser(email));

        var found = repository.findByEmail(email);

        assertThat(found)
                .as("findByEmail should return the saved user")
                .isPresent()
                .get()
                .extracting(User::getId, User::getEmail, User::getPasswordDigest)
                .containsExactly(saved.getId(), email, saved.getPasswordDigest());
    }
}
