create table users (
    id              bigint generated by default as identity primary key,
    first_name      varchar(255) not null,
    last_name       varchar(255) not null,
    email           varchar(255) not null,
    password_digest varchar(255) not null,
    created_at timestamp not null default now(),
    updated_at timestamp not null default now(),
    constraint uk_users_email unique (email)
);